--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 4/15/2026 9:19:29 AM
-- Server version: 10.4.28
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE misaemployee_development;

--
-- Drop procedure `Proc_Department_FilterPaging`
--
DROP PROCEDURE IF EXISTS Proc_Department_FilterPaging;

--
-- Drop table `employee`
--
DROP TABLE IF EXISTS employee;

--
-- Drop table `position`
--
DROP TABLE IF EXISTS position;

--
-- Drop procedure `Proc_DeleteDepartmentById`
--
DROP PROCEDURE IF EXISTS Proc_DeleteDepartmentById;

--
-- Drop procedure `Proc_InsertDepartment`
--
DROP PROCEDURE IF EXISTS Proc_InsertDepartment;

--
-- Drop procedure `Proc_UpdateDepartment`
--
DROP PROCEDURE IF EXISTS Proc_UpdateDepartment;

--
-- Drop table `department`
--
DROP TABLE IF EXISTS department;

--
-- Set default database
--
USE misaemployee_development;

--
-- Create table `department`
--
CREATE TABLE department (
  DepartmentID char(36) NOT NULL COMMENT 'Khóa chính phòng ban',
  DepartmentCode varchar(20) NOT NULL COMMENT 'Mã phòng ban',
  DepartmentName varchar(255) NOT NULL COMMENT 'Tên phòng ban',
  Description varchar(255) DEFAULT NULL COMMENT 'Diễn giải',
  PRIMARY KEY (DepartmentID)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `UQ_DepartmentCode` on table `department`
--
ALTER TABLE department
ADD UNIQUE INDEX UQ_DepartmentCode (DepartmentCode);

DELIMITER $$

--
-- Create procedure `Proc_UpdateDepartment`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_UpdateDepartment (IN v_DepartmentID char(36),
IN v_DepartmentCode varchar(20),
IN v_DepartmentName varchar(255),
IN v_Description varchar(255))
BEGIN
  -- Kiểm tra tồn tại
  IF NOT EXISTS (SELECT
        1
      FROM department
      WHERE DepartmentID = v_DepartmentID) THEN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = 'Department không tồn tại';
  END IF;

  -- Kiểm tra trùng code (trừ chính nó)
  IF EXISTS (SELECT
        1
      FROM department
      WHERE DepartmentCode = v_DepartmentCode
      AND DepartmentID <> v_DepartmentID) THEN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = 'DepartmentCode đã tồn tại';
  END IF;

  -- Update
  UPDATE department
  SET DepartmentCode = v_DepartmentCode,
      DepartmentName = v_DepartmentName,
      Description = v_Description
  WHERE DepartmentID = v_DepartmentID;

END
$$

--
-- Create procedure `Proc_InsertDepartment`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_InsertDepartment (IN v_DepartmentID char(36),
IN v_DepartmentCode varchar(20),
IN v_DepartmentName varchar(255),
IN v_Description varchar(255))
BEGIN
  -- Kiểm tra trùng mã phòng ban
  IF EXISTS (SELECT
        1
      FROM department
      WHERE DepartmentCode = v_DepartmentCode) THEN
    SIGNAL SQLSTATE '45000'
    SET MESSAGE_TEXT = 'DepartmentCode đã tồn tại';
  ELSE
    INSERT INTO department (DepartmentID,
    DepartmentCode,
    DepartmentName,
    Description)
      VALUES (v_DepartmentID, v_DepartmentCode, v_DepartmentName, v_Description);
  END IF;
END
$$

--
-- Create procedure `Proc_DeleteDepartmentById`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_DeleteDepartmentById (IN v_DepartmentID char(36))
BEGIN
  DELETE
    FROM Department
  WHERE DepartmentID = v_DepartmentID;
END
$$

DELIMITER ;

--
-- Create table `position`
--
CREATE TABLE position (
  PositionID char(36) NOT NULL COMMENT 'Khóa chính chức vụ',
  PositionCode varchar(20) NOT NULL COMMENT 'Mã chức vụ',
  PositionName varchar(255) NOT NULL COMMENT 'Tên chức vụ',
  PRIMARY KEY (PositionID)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

--
-- Create index `UQ_PositionCode` on table `position`
--
ALTER TABLE position
ADD UNIQUE INDEX UQ_PositionCode (PositionCode);

--
-- Create table `employee`
--
CREATE TABLE employee (
  EmployeeID char(36) NOT NULL COMMENT 'Khóa chính nhân viên',
  EmployeeCode varchar(20) NOT NULL COMMENT 'Mã nhân viên',
  EmployeeName varchar(100) NOT NULL COMMENT 'Tên nhân viên',
  Gender int(11) DEFAULT 0 COMMENT 'Giới tính: 0-Nữ, 1-Nam, 2-Khác',
  DateOfBirth date DEFAULT NULL COMMENT 'Ngày sinh',
  PhoneNumber varchar(50) DEFAULT NULL COMMENT 'Số điện thoại',
  Email varchar(100) DEFAULT NULL COMMENT 'Email',
  Address varchar(255) DEFAULT NULL COMMENT 'Địa chỉ',
  DepartmentID char(36) NOT NULL COMMENT 'Phòng ban',
  PositionID char(36) NOT NULL COMMENT 'Chức vụ',
  Salary decimal(18, 4) DEFAULT 0.0000 COMMENT 'Lương cơ bản',
  CreatedDate datetime DEFAULT NULL COMMENT 'Ngày tạo',
  HireDate datetime DEFAULT NULL COMMENT 'Ngày tuyển dụng'
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_general_ci;

DELIMITER $$

--
-- Create procedure `Proc_Department_FilterPaging`
--
CREATE DEFINER = 'root'@'localhost'
PROCEDURE Proc_Department_FilterPaging (IN v_pageIndex int,
IN v_pageSize int,
IN v_search varchar(255),
IN v_sort varchar(200),
IN v_searchFields json)
BEGIN

  DECLARE v_offset int;
  DECLARE v_where text DEFAULT ' WHERE 1=1 ';
  DECLARE v_orderBy text DEFAULT '';
  DECLARE v_searchCondition text;

  -- 1️⃣ Paging cơ bản
  IF v_pageIndex < 1 THEN
    SET v_pageIndex = 1;
  END IF;
  IF v_pageSize < 1 THEN
    SET v_pageSize = 20;
  END IF;

  SET v_offset = (v_pageIndex - 1) * v_pageSize;

  -- 2️⃣ Search nhiều field
  IF v_search IS NOT NULL
    AND v_search <> ''
    AND v_searchFields IS NOT NULL THEN

    SELECT
      GROUP_CONCAT(
      CONCAT(
      '`',
      JSON_UNQUOTE(JSON_EXTRACT(v_searchFields, CONCAT('$[', n, ']'))),
      '` LIKE "%', v_search, '%"'
      )
      SEPARATOR ' OR '
      ) INTO v_searchCondition
    FROM (SELECT
        0 n
      UNION
      SELECT
        1
      UNION
      SELECT
        2
      UNION
      SELECT
        3
      UNION
      SELECT
        4) t
    WHERE n < JSON_LENGTH(v_searchFields);

    IF v_searchCondition IS NOT NULL THEN
      SET v_where = CONCAT(v_where, ' AND (', v_searchCondition, ')');
    END IF;

  END IF;

  -- 3️⃣ Sort nhiều cột
  IF v_sort IS NOT NULL
    AND v_sort <> '' THEN

    SELECT
      GROUP_CONCAT(
      CONCAT(
      '`', SUBSTRING(item, 2), '` ',
      IF(LEFT(item, 1) = '-', 'DESC', 'ASC')
      )
      SEPARATOR ', '
      ) INTO v_orderBy
    FROM (SELECT
        TRIM(SUBSTRING_INDEX (SUBSTRING_INDEX (v_sort, ',', n), ',', -1)) item
      FROM (SELECT
          1 n
        UNION
        SELECT
          2
        UNION
        SELECT
          3
        UNION
        SELECT
          4) x
      WHERE n <= 1 + LENGTH(v_sort) - LENGTH(REPLACE(v_sort, ',', ''))) y;

    IF v_orderBy IS NOT NULL THEN
      SET v_orderBy = CONCAT(' ORDER BY ', v_orderBy);
    END IF;

  END IF;

  -- 4️⃣ Default sort
  IF v_orderBy IS NULL
    OR v_orderBy = '' THEN
    SET v_orderBy = ' ORDER BY DepartmentID DESC';
  END IF;

  -- 5️⃣ Build SQL
  SET @v_sql = CONCAT(
  'SELECT * FROM Department ',
  v_where,
  v_orderBy,
  ' LIMIT ', v_offset, ',', v_pageSize, '; '
  );


  -- 6. SQL count
  SET @v_sqlCount = CONCAT(
  'SELECT COUNT(*) AS Total FROM Department ',
  v_where
  );



  PREPARE stmt1 FROM @v_sql;
  EXECUTE stmt1;
  DEALLOCATE PREPARE stmt1;

  PREPARE stmt FROM @v_sqlCount;
  EXECUTE stmt;
  DEALLOCATE PREPARE stmt;


END
$$

DELIMITER ;

-- 
-- Dumping data for table position
--
-- Table misaemployee_development.position does not contain any data (it is empty)

-- 
-- Dumping data for table employee
--
-- Table misaemployee_development.employee does not contain any data (it is empty)

-- 
-- Dumping data for table department
--
INSERT INTO department VALUES
('550e8400-e29b-41d4-a716-446655440000', 'HRM', 'Human Resources', 'Quản lý nhân sự'),
('550e8400-e29b-41d4-a716-446655440001', 'HRM2', 'Finance', 'Quản lý tài chính'),
('550e8400-e29b-41d4-a716-446655440002', 'IT', 'Information Technology', 'Quản lý hệ thống CNTT'),
('550e8400-e29b-41d4-a716-446655440003', 'MKT', 'Marketing', 'Quảng bá và tiếp thị'),
('550e8400-e29b-41d4-a716-446655440004', 'OPS', 'Operations', 'Vận hành doanh nghiệp');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;